---
title: "main"
author: "Nils Brun"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load data
library(readr)

data_srf <- read_tsv("../data/dataset.tsv")
```
```{r}
# Make the "head" column lowercase
data_srf$head_lower <- tolower(data_srf$head)
data_srf$content_lower <- tolower(data_srf$content)
```

```{r}
#Load the stringr package
library(stringr)

#Count the occurrences of "hamas" in each entry of the "head" and "content" column, case insensitive
data_srf$head_count_hamas <- str_count(tolower(data_srf$head), "hamas")
data_srf$content_count_hamas <- str_count(tolower(data_srf$content), "hamas")

#Count the occurrences of "israel" in each entry of the "head" and "content" column, case insensitive
data_srf$head_count_israel <- str_count(tolower(data_srf$head), "israel")
data_srf$content_count_israel <- str_count(tolower(data_srf$content), "israel")

#change all "ä" to "ae" in the "head" and "content" column
data_srf$head <- str_replace_all(data_srf$head, "\u00e4", "ae")
data_srf$content <- str_replace_all(data_srf$content, "\u00e4", "ae")
#Count the occurrence of "Palästina" in each entry of the "head" and "content column, case insensitive
data_srf$head_count_palaestina <- str_count(tolower(data_srf$head), "palaestina")
data_srf$content_count_palaestina <- str_count(tolower(data_srf$content), "palaestina")

#Count the occurrence of "Gaza" in each entry of the "head" and "content column, case insensitive
data_srf$head_count_gaza <- str_count(tolower(data_srf$head), "gaza")
data_srf$content_count_gaza <- str_count(tolower(data_srf$content), "gaza")

#Count the occurence of "Genozid" in each entry of the "head" and "content" column, case insensitive
data_srf$head_count_genozid <- str_count(tolower(data_srf$head), "genozid")
data_srf$content_count_genozid <- str_count(tolower(data_srf$content), "genozid")

#Count the occurence of "Krieg" in each entry of the "head" and "content" column, case insensitive
data_srf$head_count_krieg <- str_count(tolower(data_srf$head), "krieg")
data_srf$content_count_krieg <- str_count(tolower(data_srf$content), "krieg")

#Count the occurence of "Terrorismus" in each entry of the "head" and "content" column, case insensitive
data_srf$head_count_terrorismus <- str_count(tolower(data_srf$head), "terrorismus")
data_srf$content_count_terrorismus <- str_count(tolower(data_srf$content), "terrorismus")
```

```{r}
#change the formate of the pubtime variable
data_srf$pubtime <- as.Date(data_srf$pubtime)
```

```{r}
write_tsv(data_srf, "../data_prep/data_srf_prep.tsv")
```
